config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  
  resources :users, only: [:index, :edit, :update]
  resources :groups, only: [:index, :new, :create, :edit, :update, :destroy] do
    resources :messages, only: [:index, :create, :destroy]
    namespace :api do
      resources :messages, only: :index, defaults: { format: 'json' }
    end
    resources :tweets do
      collection do
        get 'search'
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users
  has_many :messages,dependent: :destroy
  has_many :tweets,dependent: :destroy
  validates :name, presence: true, uniqueness: {case_sensitive: true}

  def show_last_message
    if (last_message = messages.last).present?
      if last_message.content?
        last_message.content
      else
        '画像が投稿されています'
      end
    else
      'まだメッセージはありません。'
    end
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user
  validates :content, presence: true, unless: :image?

  mount_uploader :image, ImageUploader
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :group,optional: true,dependent: :destroy
  belongs_to :user,optional: true
  
  validates :text, presence: true

  def self.search(search)
    if search
      Tweet.where('text LIKE(?)', "%#{search}%")
    else
      Tweet.all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :group_users, dependent: :destroy
  has_many :groups, through: :group_users
  has_many :messages, dependent: :destroy
  has_many :tweets,dependent: :destroy
end

app/controllers/api/messages_controller.rb
class Api::MessagesController < ApplicationController
  def index
    group = Group.find(params[:group_id])
    last_message_id = params[:id]
    @messages = group.messages.includes(:user).where("id > ?", last_message_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def index
    @groups = Group.all 
  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: 'ポイントを作成しました'
    else
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to root_path, notice: 'ポイント名を更新しました'
    else
      render :edit
    end
  end

  def destroy
    group = Group.find(params[:id])
    group.destroy
    redirect_to root_path, notice: 'ポイントを削除しました'
  end

  private
  def group_params
    params.require(:group).permit(:name, user_ids: [])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group

  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
    @groups = Group.all
  end

  def create
    @message = @group.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.json
      end
    else
      @messages = @group.messages.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください。'
      render :index
    end
  end

  def destroy
  end

  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:edit, :show]
  before_action :set_group
  # before_action :move_to_index, except: [:index, :show, :search]

  def index
    @tweets = Tweet.includes(:user).order("created_at DESC")
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.create(tweet_params)
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
  end

  def edit
  end

  def update
    tweet = Tweet.find(params[:id])
    tweet.update(tweet_params)
  end

  def show
  end

  def search
    @tweets = Tweet.search(params[:keyword])
  end
  
  private
  def tweet_params
    params.require(:tweet).permit(:name, :image, :text, :user_id, :group_id).merge(user_id: current_user.id)
  end

  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    return nil if params[:keyword] == ""
    @users = User.where(['name LIKE ?', "%#{params[:keyword]}%"] ).where.not(id: current_user.id).limit(10)
    respond_to do |format|
      format.html
      format.json
    end
    # @tweets = current_user.tweets
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_with model: group, local: true do |f|
  - if group.errors.any?
    .SettingGroupForm__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - group.errors.full_messages.each do |message|
          %li= message
  .SettingGroupForm__field
    -# .SettingGroupForm__leftField
    -#   = f.label :name, class: 'SettingGroupForm__label'
    .SettingGroupForm__rightField
      = f.text_field :name, class: 'SettingGroupForm__input', placeholder: 'ポイント名を入力してください'
  -# .SettingGroupForm__field
  -#   .SettingGroupForm__leftField
  -#     %label.SettingGroupForm__label チャットメンバーを追加
  -#   .SettingGroupForm__rightField
  -#     .UserSearch
  -#       %input#UserSearch__field.SettingGroupForm__input{placeholder: "追加したいユーザー名を入力してください", type: "text"}/
  -#     #UserSearchResult
  -# .SettingGroupForm__field
  -#   .SettingGroupForm__leftField
  -#     = f.label :name, value: "チャットメンバー", class: "SettingGroupForm__label"
  -#   .SettingGroupForm__rightField
  -#     .ChatMembers
  -#       .ChatMember
  -#       %p.ChatMember__name= current_user.name
  -#       %input{name: "group[user_ids][]", type: "hidden", value: current_user.id}
  .SettingGroupForm__field
    .SettingGroupForm__leftField
    .SettingGroupForm__rightField
      = f.submit class: 'SettingGroupForm__button'
    .RightHeader__Button
      = link_to "削除する",group_path, method: :delete
    .Back__Button
      .RightHeader__Button__back
        = link_to "戻る", :back, class: 'Button'

app/views/groups/edit.html.haml
.SettingGroupForm
  .Backform
    .Backform__center
      .Backform__center__logo
        ポイント名 編集 削除
        = render partial: 'form', locals: { group: @group }

app/views/groups/index.html.haml
.Wrapper
  = render 'messages/side_bar'
  = render 'messages/backs'

app/views/groups/new.html.haml
.SettingGroupForm
  %h1 新規チャットグループ
  = render partial: 'form', locals: { group: @group }

app/views/layouts/_notifications.html.haml
-# .Notification
-#   - flash.each do |key, value|
-#     = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Surf-Chat
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application'
  %body
    = render 'layouts/notifications'
    = yield

app/views/messages/_backs.html.haml
.Backs
  .Back
    .Back__Message
      SRAF-CHAT

app/views/messages/_main_chat.html.haml
.Chat
  .RightHeader
    .RightHeader__group
      .RightHeader__groupName
        = link_to group_tweets_path(@group) do
          = @group.name
      
        

    .RightHeader__editButton
      = link_to edit_group_path(@group) do
        EDIT 

  .MessageField
    = render @messages

  .Footer
    = form_with model: [@group, @message], html: {classr: "Form"}, local: true do |f|
      .Form__contents
        = f.text_area :content, class: 'Form__inputContent', placeholder: '波情報を入力'
        = f.label :image, class: 'Form__inputImage' do
          = icon('far', 'image', class: 'Form__icon')
          = f.file_field :image, class: 'Hiddens'
      = f.submit '送信', class: 'Form__submit'

app/views/messages/_message.html.haml
.MessageBox{data: {message: {id: message.id}}}
  .MessageInfo
    .MessageInfo__userName
      = message.user.name
    .MessageInfo__date
      = message.created_at.strftime("%Y年%m月%d日 %H時%M分")
  .Message
    - if message.content.present?
      %p.Message__content
        = message.content
    = image_tag message.image.url, class: 'Message__image' if message.image.present?

app/views/messages/_side_bar.html.haml
.SideBar
  .LeftHeader
    .LeftHeader__list
      %h3.LeftHeader__userName
        = current_user.name
      %ul.LeftHeader__iconList
        %li.LeftHeader__Icon
          = link_to edit_user_path(current_user) do
            = icon('fas', 'anchor')
        -# %li.LeftHeader__Icon
        -#   = link_to new_group_path do
        -#     = icon('fas', 'edit')
  .GroupList
    .Point 湘南エリア
    -# - current_user.groups.each do |group|
    - @groups.each do |group|
      .Group
        = link_to group_messages_path(group) do
          .Group__name
            = group.name
          -# .Group__message
          -#   = group.show_last_message

app/views/messages/index.html.haml
= javascript_include_tag 'autoReload'
.Wrapper
  = render "side_bar"
  = render "main_chat"

app/views/tweets/create.html.haml
.backs__images
  .contents.row
    .success
      %h3 投稿が完了しました。
      .links__btn
        %a.btn
          = link_to group_tweets_path(@group) do
            一覧へ戻る

app/views/tweets/destroy.html.haml
.backs__images
  .contents.row
    .success
      %h3 削除が完了しました。
      .links__btn
        %a.btn
          = link_to '一覧へ戻る', group_tweets_path(@group)

app/views/tweets/edit.html.haml
.back__image
  .contents.row
    .container
      .form__wish
        = form_with model: [@group, @tweet], local: true do |form|
          %h3 編集する
          .input-box
          = form.text_field :image, placeholder: "Image Url", class: 'input-image'
          = form.text_area :text, placeholder: "text", rows: "10", class: 'input-text'
          = form.submit "編集", class: 'submit-bttom'

app/views/tweets/index.html.haml
.body
  .group__title
    .group__title__name
      = @group.name
  .links
    .links__post
      %a.post
        = link_to '投稿する', new_group_tweet_path
    .links__btn
      %a.btn
        = link_to "波情報に戻る", groups_path
  = form_with url: search_group_tweets_path, local: true, method: :get, class: "search-form" do |form|
    = form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input"
    = form.submit "検索", class: "search-btn"
  .contents.row
    - @tweets.each do |tweet|
      .content_post{style: "background-image: url(#{tweet.image});"}
        -# - if user_signed_in? && current_user.id == tweet.user_id
        .more
          %ul.more_list
            %li
              = link_to '編集', edit_group_tweet_path(@group,tweet.id), method: :get
            %li
              = link_to '削除', group_tweet_path(@group,tweet.id), method: :delete
      .comments
        .spanclass
          %spam.name= tweet.user.name
        .textclass
          %p= tweet.text

app/views/tweets/new.html.haml
.back__images
  .contents.row.edit
    .container
      .form__wish
        = form_with model: [@group, @tweet], local: true do |form|
          %h3 投稿する
          .input-box
          = form.text_field :image, placeholder: "Image Url", class: 'input-image'
          -#   = form.label :image, class: 'Form__inputImage' do
          -#     = icon('far', 'image', class: 'Form__icon')
          -#     = form.file_field :image, class: 'Hiddens'
          = form.text_area :text, placeholder: "text", rows: "10", class: 'input-text'
          = form.submit "投稿", class: 'submit-bttom'

app/views/tweets/search.html.haml
.body
  .group__title
    .group__title__name
      = @group.name
  .links
    .links__post
      %a.post
        = link_to "戻る", :back
    .links__btn
      %a.btn
        = link_to "波情報に戻る", groups_path
  = form_with url: search_group_tweets_path, local: true, method: :get, class: "search-form" do |form|
    = form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input"
    = form.submit "検索", class: "search-btn"
  .contents.row
    - @tweets.each do |tweet|
      .content_post{style: "background-image: url(#{tweet.image});"}
        - if user_signed_in? && current_user.id == tweet.user_id
          .more
            %ul.more_list
              %li
                = link_to '編集', edit_group_tweet_path(@group,tweet.id), method: :get
              %li
                = link_to '削除', group_tweet_path(@group,tweet.id), method: :delete
      .comments
        .spanclass
          %spam.name= tweet.user.name
        .textclass
          %p= tweet.text

app/views/tweets/show.html.haml
.contents.row
  .content_post{style: "background-image: url(#{@tweet.image});"}
    .more
      %ul.more_list
        %li
          = link_to '編集', edit_group_tweet_path(@group,@tweet), method: :get
        %li
          = link_to '削除', group_tweet_path(@group,@tweet), method: :delete
    %p= @tweet.text
    %span.name
      = @tweet.name

app/views/tweets/update.html.haml
.backs__images
  .contents.row
    .success
      %h3 更新が完了しました。
      .links__btn
        %a.btn
          = link_to '一覧へ戻る', group_tweets_path(@group)

app/views/users/edit.html.haml
.AccountPage
  .AccountPage__title
    %h2 SURFーCHAT
    %h5 アカウントの編集
    = link_to "ログアウト",  destroy_user_session_path, method: :delete, class: 'Button'
    = link_to "波情報に戻る", :back, class: 'Button'
  .AccountPage__form
    = form_for(current_user) do |f|
      .FormField
        .FormField__label--normal
          = f.label :name
        .FormField__input--normal
          = f.text_field :name, autofocus: true
      .FormField
        .FormField__label--normal
          = f.label :email
        .FormField__input--normal
          = f.email_field :email
      = f.submit "Update", class: 'Button UserButton'